### ISSUE TITLE
Converting the whole thing to jekyll

### ISSUE THREAD

**Issue by sahin** [basecamp/policies#14]
Hi,

We are so happy that Basecamp did smth like this. So amazing. We will use it in [Remoteteam.com](https://www.remoteteam.com)

I started to copy-pasting , replacing basecamp with Remote Team. It sort of need some work :). Change email, company name, etc etc, links ( they are all like /security/overview.md)

will you guys be ok to make this totally a jekyll site and make company name, email as variables. ?

**Comment by jeremy** [comment]
@sahin It's pulled from a Jekyll site, in fact. 😂

A Jekyll site's sources are harder to browse, read, and contribute to, however. Our primary audience is our customers. Reuse and sharing are secondary, so we generally won't sacrifice the primary aims to make the policies easier to use as a template. That doesn't mean we can't achieve both, however!

We are working on a way to include these Markdown files directly in our own Jekyll templates so we don't have to translate changes back to our own site. We'll include what we develop in this repository so you can reuse it. Happy to take pull requests to help achieve this, too, if you come up with your own way!

Our Jekyll site will have pages that simply include the policy markdown:
```
_source/about/policies/privacy/index.md 
---
title: Basecamp privacy policy

layout: sheet
---
{% include policies/privacy.md %}
```

Where the `policies` directory is synced from this git repository using a git submodule or git subtree merge.

However, Markdown links don't work directly in Jekyll, so we'll still need some work, likely using the https://github.com/benbalter/jekyll-relative-links plugin to convert Markdown links to Jekyll links.
