### ISSUE TITLE
Open sourcing the Basecamp DPA in hellosign

### ISSUE THREAD

**Issue by sahin** [basecamp/policies#17]
It will be super duper great if you guys can add Basecamp DPA in hellosign, in github and open source it. 

https://app.hellosign.com/s/c0908a3d

**Comment by sahin** [comment]
Even for now, unformatted version will be fine. We would love to use as soon as possible.

**Comment by clarkeash** [comment]
Hey @jeremy do you still plan to do this?

**Comment by jeremy** [comment]
@clarkeash @sahin Yes! Obviously not getting to the Markdown conversion 😆 so I'll add the PDF itself, to be clear that it falls under the same license. It'll just need more work to adapt to your organization.
