### ISSUE TITLE
Suggestion: Attribution Example

### ISSUE THREAD

**Issue by ankane** [basecamp/policies#30]
Hey, thanks for this great repo! It'd be great if more companies had policies that users can actually understand (a friend recently suggested companies should require developers to read their company's privacy policy when they start and when it changes).

It'd be great to have an example of preferred attribution in the readme. Here's a minimal one I came up with based on the "pretty good attribution" example in the [Creative Commons wiki](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution):

Adapted from [Basecamp](https://github.com/basecamp/policies) / [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

Let me know what you think.

Edit: I imagine the ideal case for most companies is no attribution (to appear more professional), but the current license doesn't allow for that. I'm not sure if that's a possibility (as the current license is already generous), but wanted to throw it out there. For instance, GitHub's [balanced employee IP agreement](https://github.com/github/balanced-employee-ip-agreement) is CC0 (public domain).

**Comment by jeremy** [comment]
That's great! I'll add a note to the README.

Agreed re. the no-attribution ideal case when using these policies as a starting point, particularly when published. CC0 is a big step to take, though. We'd like to communicate "be reasonable and unobtrusive" but license language doesn't accommodate that.

**Comment by ankane** [comment]
Great, thanks @jeremy!
