### ISSUE TITLE
We do and will not

### ISSUE THREAD

**Issue by decurtic** [basecamp/policies#43]
In policies/privacy/index.md,
under **Your Rights With Respect to Your Information**,
the first line of **Right to Non-Discrimination** reads 
"This right stems from the CCPA. We do and will not charge you a different amount..."
I assume it should read "We do **not** and will not..."

BTW thanks for sharing this!

**Comment by janejuenyang** [comment]
Thanks so much for flagging @decurtic! Fixing in https://github.com/basecamp/policies/pull/45.
