### ISSUE TITLE
Broken researchers list

### ISSUE THREAD

**Issue by czhc** [basecamp/policies#8]
https://github.com/basecamp/policies/blob/master/security/vulnerability-response.md

List of researchers are not rendering correctly.

![screenshot 2018-12-15 at 4 44 31 pm](https://user-images.githubusercontent.com/4633021/50041015-ecce3500-0088-11e9-90f7-cb3ce69a1104.png)

**Comment by jeremy** [comment]
Right! This is our Jekyll template pulling from a dataset. Switching to a literal listing 👍🏼

**Comment by sahin** [comment]
@jeremy , to be honest, it will be way better to get names from data source. I actually want to start to move some things like company , emails to data. 

If they are in the data, it supports 2 kinds group of people ( who wants to copy paste or who can run jeklly)

**Comment by jeremy** [comment]
Using data is really convenient, @sahin! It's important that our customers can browse this GitHub repository and have it render correctly, though, so using plain Markdown is OK with us. When we sync with our Jekyll repository, we use the data form.

**Comment by sahin** [comment]
@jeremy got it. Can you guys share the Jekyll source. 

Is it possible to add _source (folder/new repo/branch) for Jekyll source, and keep the original this one as text.
