### ISSUE TITLE
Broken 'contact us' link

### ISSUE THREAD

**Issue by akshayKhot** [basecamp/policies#92]
The contact us link on the [what happens when you cancel?](https://github.com/basecamp/policies/blob/master/cancellation/index.md#what-happens-when-you-cancel) page is broken.

**Comment by jeremy** [comment]
Thanks for reporting! These policy documents are *mostly* standalone; this is an example of where there are not. The policy is directly included in the basecamp.com site where this variable is defined, resulting in a link to support@basecamp.com on https://basecamp.com/about/policies/cancellation.

**Comment by akshayKhot** [comment]
Ah, I see. Thanks for the information.
